schema_version: 1

context:
  python_min: "3.12"
  version: "1.2.1"

package:
  name: adaptivetesting
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/a/adaptivetesting/adaptivetesting-${{ version }}.tar.gz
  sha256: 3e7034a5675bd2d94ae5548424f4dc9b83409f98cb8e18acdfd20b90d6a27bd0

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - pip
    - setuptools
    - cython
  run:
    - python >=${{ python_min }}
    - numpy >=2.1.0
    - pandas >=2.3.0
    - scipy >=1.15.0
    - tqdm >=4.66.0
    - matplotlib-base >=3.10.0
    - numdifftools >=0.9.42

tests:
  - python:
      imports:
        - adaptivetesting
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      - pip check

about:
  summary: adaptivetesting is a Python package that can be used to simulate and evaluate custom CAT scenarios as well as implement them in real-world testing scenarios from a single codebase
  license: MPL-2.0
  license_file: LICENSE
  homepage: https://github.com/condecon/adaptivetesting
  documentation: https://github.com/condecon/adaptivetesting/tree/main/docs

extra:
  recipe-maintainers:
    - condecon
